/*
Copyright 2021 The Kruise Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	scheme "github.com/openkruise/controllermesh-api/client/clientset/versioned/scheme"
	v1alpha1 "github.com/openkruise/controllermesh-api/ctrlmesh/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ManagerStatesGetter has a method to return a ManagerStateInterface.
// A group's client should implement this interface.
type ManagerStatesGetter interface {
	ManagerStates() ManagerStateInterface
}

// ManagerStateInterface has methods to work with ManagerState resources.
type ManagerStateInterface interface {
	Create(*v1alpha1.ManagerState) (*v1alpha1.ManagerState, error)
	Update(*v1alpha1.ManagerState) (*v1alpha1.ManagerState, error)
	UpdateStatus(*v1alpha1.ManagerState) (*v1alpha1.ManagerState, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.ManagerState, error)
	List(opts v1.ListOptions) (*v1alpha1.ManagerStateList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ManagerState, err error)
	ManagerStateExpansion
}

// managerStates implements ManagerStateInterface
type managerStates struct {
	client rest.Interface
}

// newManagerStates returns a ManagerStates
func newManagerStates(c *CtrlmeshV1alpha1Client) *managerStates {
	return &managerStates{
		client: c.RESTClient(),
	}
}

// Get takes name of the managerState, and returns the corresponding managerState object, and an error if there is any.
func (c *managerStates) Get(name string, options v1.GetOptions) (result *v1alpha1.ManagerState, err error) {
	result = &v1alpha1.ManagerState{}
	err = c.client.Get().
		Resource("managerstates").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ManagerStates that match those selectors.
func (c *managerStates) List(opts v1.ListOptions) (result *v1alpha1.ManagerStateList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.ManagerStateList{}
	err = c.client.Get().
		Resource("managerstates").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested managerStates.
func (c *managerStates) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("managerstates").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a managerState and creates it.  Returns the server's representation of the managerState, and an error, if there is any.
func (c *managerStates) Create(managerState *v1alpha1.ManagerState) (result *v1alpha1.ManagerState, err error) {
	result = &v1alpha1.ManagerState{}
	err = c.client.Post().
		Resource("managerstates").
		Body(managerState).
		Do().
		Into(result)
	return
}

// Update takes the representation of a managerState and updates it. Returns the server's representation of the managerState, and an error, if there is any.
func (c *managerStates) Update(managerState *v1alpha1.ManagerState) (result *v1alpha1.ManagerState, err error) {
	result = &v1alpha1.ManagerState{}
	err = c.client.Put().
		Resource("managerstates").
		Name(managerState.Name).
		Body(managerState).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *managerStates) UpdateStatus(managerState *v1alpha1.ManagerState) (result *v1alpha1.ManagerState, err error) {
	result = &v1alpha1.ManagerState{}
	err = c.client.Put().
		Resource("managerstates").
		Name(managerState.Name).
		SubResource("status").
		Body(managerState).
		Do().
		Into(result)
	return
}

// Delete takes name of the managerState and deletes it. Returns an error if one occurs.
func (c *managerStates) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("managerstates").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *managerStates) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("managerstates").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched managerState.
func (c *managerStates) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ManagerState, err error) {
	result = &v1alpha1.ManagerState{}
	err = c.client.Patch(pt).
		Resource("managerstates").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
